
def _KEY(word, val=None):
    return ("KEY", word, val)

def _SEQ(*items, **args):
    return ("SEQ", items, args)

def _STRUCT(item):
    return ("STRUCT", item)

def _CHOICE(*items):
    return ("CHOICE", items)

def _OPT(item, **args):
    return ("OPT", item, args)

def _REPEAT(item):
    return ("REPEAT", item)

def _ARRAY(item, num=None):
    return ("ARRAY", item, num)

def _VAR(item, name):
    return ("VAR", item, name)

def _NSEQ(*items):
    return ("NSEQ", items)

def _NOTNEXT(item):
    return ("NOTNEXT", item)

_EOL = ("EOL", ) # end of line mark used for writing only

_END_CMD = _SEQ(_KEY(";"), _EOL)

_def_parse_schema = {
    "FILE": _SEQ(_VAR(_STRUCT("HDR"), "Hdr"), _VAR(_STRUCT("DESIGN"), "Design")),
    "HDR": _NSEQ("VERSION_CMD", "DIVIDERCHAR_CMD", "BUSBITCHARS_CMD"),
    "VERSION_CMD": _SEQ(_KEY("VERSION"), _VAR(str, "Version"), _END_CMD),
    "DIVIDERCHAR_CMD": _SEQ(_KEY("DIVIDERCHAR"), _VAR(str, "Divider"), _END_CMD),
    "BUSBITCHARS_CMD": _SEQ(_KEY("BUSBITCHARS"), _VAR(str, "BusBitsChars"), _END_CMD),
    "DESIGN": _SEQ("DESIGN_CMD", "DESIGN_INFO", _VAR(_ARRAY("DESIGN_ITEM"),"Items"), "ENDDESIGN_CMD"),
    "DESIGN_CMD": _SEQ(_KEY("DESIGN"), _VAR(str, "Name"), _END_CMD),
    "ENDDESIGN_CMD": _SEQ(_KEY("END"), _KEY("DESIGN"), _EOL),
    "DESIGN_ITEM": _CHOICE("ROW_CMD", "TRACKS_CMD", "VIAS", "COMPONENTS", "PINS", "BLOCKAGES", "SPECNETS", "NETS"),
    "DESIGN_INFO": _NSEQ("UNITS_CMD", "DIEAREA_CMD"),
    "UNITS_CMD": _SEQ(_KEY("UNITS"), _KEY("DISTANCE"), _KEY("MICRONS"), _VAR(int, "Dbu"), _END_CMD),
    "DIEAREA_CMD": _SEQ(_KEY("DIEAREA"), _VAR(_ARRAY("XY"), "DieArea"), _END_CMD),
    "XY": _SEQ(_KEY('('), _ARRAY(int, 2), _KEY(')')),
    "ORIENT": _CHOICE(_KEY("N", "North"),
                      _KEY("S", "South"),
                      _KEY("E", "East"),
                      _KEY("W", "West"),
                      _KEY("FN", "FlipNorth"),
                      _KEY("FS", "FlipSouth"),
                      _KEY("FE", "FlipEast"),
                      _KEY("FW", "FlipWest")),
    "ROW_CMD": _STRUCT(_SEQ(_KEY("ROW"), _VAR(str, "Name"), _VAR(str, "Site"),
                       _VAR(_ARRAY(int, 2), "Origin"), _VAR("ORIENT", "Orient"),
                       _OPT(_SEQ(_KEY("DO"), _VAR(int, "NX"), _KEY("BY"), _VAR(int, "NY"),
                       _OPT(_SEQ(_KEY("STEP"), _VAR(int, "DX"), _VAR(int, "DY"))))), _END_CMD, Type="Row")),
    "TRACKS_CMD": _STRUCT(_SEQ(_KEY("TRACKS"),
                               _CHOICE(_SEQ(_KEY("X"), _VAR(int, "X"),
                                            _KEY("DO"), _VAR(int, "NX"),
                                            _KEY("STEP"), _VAR(int, "DX"),
                                            Direction="Vertical", Y=0, NY=1, DY=0),
                                       _SEQ(_KEY("Y"), _VAR(int, "Y"),
                                            _KEY("DO"), _VAR(int, "NY"),
                                            _KEY("STEP"), _VAR(int, "DY"),
                                            Direction="Horisontal", X=0, NX=1, DX=0)),
                               _OPT(_SEQ("MASKNUM", _OPT(_KEY("SAMEMASK"), SameMask=True))),
                               _OPT(_SEQ(_KEY("LAYER"), _VAR(_ARRAY(str), "Layers"))),
                               _END_CMD, Type="Tracks")),
    "VIAS": _STRUCT(_SEQ("VIAS_CMD", _VAR(_ARRAY("VIA_CMD"), "Items"), "ENDVIAS_CMD", Type="Vias")),
    "VIAS_CMD": _SEQ(_KEY("VIAS"), _VAR(int, "Number"), _END_CMD),
    "VIA_CMD": _STRUCT(_SEQ(_KEY("-"), _VAR(str, "Name"),
                            _CHOICE("VIARULE",
                                    _VAR(_ARRAY(_CHOICE("RECT","POLYGON")), "Shapes")), _END_CMD)),
    "ENDVIAS_CMD": _SEQ(_KEY("END"), _KEY("VIAS"), _EOL),
    "VIARULE": _SEQ(_KEY("+"), _KEY("VIARULE"), _VAR(str, "Rule"),
                    _KEY("+"), _KEY("CUTSIZE"), _VAR(_ARRAY(int, 2), "CutSize"),
                    _KEY("+"), _KEY("LAYERS"), _VAR(_ARRAY(str, 3), "Layers"),
                    _KEY("+"), _KEY("CUTSPACING"), _VAR(_ARRAY(int, 2), "CutSpacing"),
                    _KEY("+"), _KEY("ENCLOSURE"), _VAR(_ARRAY(_ARRAY(int, 2), 2), "Enclosure"),
                    _OPT(_SEQ(_KEY("+"), _KEY("ROWCOL"), _VAR(_ARRAY(int, 2), "NumCuts"))),
                    _OPT(_SEQ(_KEY("+"), _KEY("ORIGIN"), _VAR(_ARRAY(int, 2), "Origin"))),
                    _OPT(_SEQ(_KEY("+"), _KEY("OFFSET"), _VAR(_ARRAY(_ARRAY(int, 2), 2), "Offset"))),
                    _OPT(_SEQ(_KEY("+"), _KEY("PATTERN"), _VAR(str, "Pattern")))),
    "RECT": _STRUCT(_SEQ(_KEY("+"), _KEY("RECT"), _VAR(str, "Layer"),
                         _OPT(_SEQ(_KEY("+"),"MASKNUM")),
                         _VAR(_ARRAY("XY", 2), "Points"), Type="Rect")),
    "MASKNUM": _SEQ(_KEY("MASK"), _VAR(int, "MaskNum")),
    "POLYGON": _STRUCT(_SEQ(_KEY("+"), _KEY("POLYGON"), _VAR(str, "Layer"),
                       _OPT(_SEQ(_KEY("+"),"MASKNUM")),
                       _VAR(_ARRAY("XY"), "Points"), Type="Polygon")),
    "COMPONENTS": _STRUCT(_SEQ("COMPONENTS_CMD", _VAR(_ARRAY("COMPONENT_CMD"), "Items"),
                               "ENDCOMPONENTS_CMD", Type="Components")),
    "COMPONENTS_CMD": _SEQ(_KEY("COMPONENTS"), _VAR(int, "Number"), _END_CMD),
    "ENDCOMPONENTS_CMD": _SEQ(_KEY("END"), _KEY("COMPONENTS"), _EOL),
    "COMPONENT_CMD": _STRUCT(_SEQ(_KEY("-"), _VAR(str, "Name"), _END_CMD)),
    "PINS": _STRUCT(_SEQ("PINS_CMD", _VAR(_ARRAY("PIN_CMD"), "Items"), "ENDPINS_CMD", Type="Pins")),
    "PINS_CMD": _SEQ(_KEY("PINS"), _VAR(int, "Number"), _END_CMD),
    "ENDPINS_CMD": _SEQ(_KEY("END"), _KEY("PINS"), _EOL),
    "PIN_CMD": _STRUCT(_SEQ(_KEY("-"), _VAR(str, "Name"), _KEY("+"), _KEY("NET"), _VAR(str, "Net"),
                            _OPT(_SEQ(_KEY("+"), _KEY("SPECIAL")), Special=True),
                            _OPT(_SEQ(_KEY("+"), _KEY("DIRECTION"),
                                      _VAR(_CHOICE(_KEY("INPUT", "Input"),
                                                   _KEY("OUTPUT", "Output"),
                                                   _KEY("INOUT", "InOut"),
                                                   _KEY("FEEDTHRU", "FeedThrough"),
                                                  ), "Direction"))),
                            _OPT(_SEQ(_KEY("+"), _KEY("NETEXPR"), _VAR(str, "NetExpr"))),
                            _OPT(_SEQ(_KEY("+"), _KEY("SUPPLYSENSITIVITY"), _VAR(str, "PowerPin"))),
                            _OPT(_SEQ(_KEY("+"), _KEY("GROUNDSENSITIVITY"), _VAR(str, "GroundPin"))),
                            _OPT("USE"),
                            _OPT(_VAR(_ARRAY(_STRUCT(_CHOICE(
                                            _SEQ(_KEY("+"), _KEY("PORT"), Type="Port"),
                                            _SEQ(_KEY("+"), _KEY("LAYER"),_VAR(str, "Layer"),
                                                 _OPT("MASKNUM"),
                                                 _OPT(_SEQ(_KEY("SPACING"), _VAR(int, "MinSpacing"))),
                                                 _OPT(_SEQ(_KEY("DESIGNRULEWIDTH"), _VAR(int, "EffectiveWidth"))),
                                                 _VAR(_ARRAY("XY", 2), "Points"),
                                                 Type="Rect"),
                                            _SEQ(_KEY("+"), _KEY("POLYGON"),_VAR(str, "Layer"),
                                                 _OPT("MASKNUM"),
                                                 _OPT(_SEQ(_KEY("SPACING"), _VAR(int, "MinSpacing"))),
                                                 _OPT(_SEQ(_KEY("DESIGNRULEWIDTH"), _VAR(int, "EffectiveWidth"))),
                                                 _VAR(_ARRAY("XY"), "Points"),
                                                 Type="Polygon"),
                                            _SEQ(_KEY("+"), _KEY("VIA"),_VAR(str, "Name"),
                                                 _OPT("MASKNUM"),
                                                 _VAR("XY", "Point"),
                                                 Type="Via"),
                                            _SEQ(_KEY("+"), _VAR(_CHOICE(_KEY("COVER", "Cover"),
                                                                         _KEY("FIXED", "Fixed"),
                                                                         _KEY("PLACED", "Placed")),
                                                                 "Placement"),
                                                 _VAR("XY", "Point"), _VAR("ORIENT", "Orient"),
                                                 Type="Placement"),
                                                    ))),
                                      "Items")),
                            _END_CMD)),
    "USE": _SEQ(_KEY("+"), _KEY("USE"),
                _VAR(_CHOICE(_KEY("SIGNAL", "Signal"),
                             _KEY("POWER", "Power"),
                             _KEY("GROUND", "Ground"),
                             _KEY("CLOCK", "Clock"),
                             _KEY("TIEOFF", "TieOff"),
                             _KEY("ANALOG", "Analog"),
                             _KEY("SCAN", "Scan"),
                             _KEY("RESET", "Reset"),
                            ), "Use")),
    "BLOCKAGES": _STRUCT(_SEQ("BLOCKAGES_CMD",
                              _VAR(_ARRAY(_CHOICE("BLOCKAGE_LAYER_CMD","BLOCKAGE_PLACEMENT_CMD")), "Items"),
                               "ENDBLOCKAGES_CMD", Type="Blockages")),
    "BLOCKAGES_CMD": _SEQ(_KEY("BLOCKAGES"), _VAR(int, "Number"), _END_CMD),
    "ENDBLOCKAGES_CMD": _SEQ(_KEY("END"), _KEY("BLOCKAGES"), _EOL),
    "BLOCKAGE_LAYER_CMD": _STRUCT(_SEQ(_KEY("-"), _KEY("LAYER"), _VAR(str, "Layer"),
                                       _NSEQ(_OPT(_SEQ(_KEY("+"), _KEY("SLOTS"), Slots=True)),
                                             _OPT(_SEQ(_KEY("+"), _KEY("FILLS"), Fills=True)),
                                             _OPT(_SEQ(_KEY("+"), _KEY("PUSHDOWN"), PushDown=True)),
                                             _OPT(_SEQ(_KEY("+"), _KEY("EXCEPTPGNET"), ExceptPowerGround=True)),
                                             _OPT(_SEQ(_KEY("+"), _KEY("COMPONENT"), Component=True)),
                                             _OPT(_SEQ(_KEY("+"), _KEY("SPACING"), MinSpacing=True)),
                                             _OPT(_SEQ(_KEY("+"), _KEY("DESIGNRULEWIDTH"), EffectiveWidth=True)),
                                             _OPT("MASKNUM")
                                       ), _VAR(_ARRAY(_STRUCT(_CHOICE(
                                                     _SEQ(_KEY("RECT"), _VAR(_ARRAY("XY", 2), "Points"), Type="Rect"),
                                                     _SEQ(_KEY("POLYGON"), _VAR(_ARRAY("XY"), "Points"), Type="Polygon")
                                                                ))), "Items"), _END_CMD, Type="Routing")),
    "BLOCKAGE_PLACEMENT_CMD": _STRUCT(_SEQ(_KEY("-"), _KEY("PLACEMENT"),
                                           _NSEQ(_OPT(_SEQ(_KEY("+"), _KEY("SOFT"), Soft=True)),
                                                 _OPT(_SEQ(_KEY("+"), _KEY("PARTIAL"), _VAR(str, "MaxDensity"))),
                                                 _OPT(_SEQ(_KEY("+"), _KEY("PUSHDOWN"), PushDown=True)),
                                                 _OPT(_SEQ(_KEY("+"), _KEY("COMPONENT"), _VAR(str, "Component")))
                                           ), _VAR(_ARRAY(_STRUCT(_CHOICE(
                                                     _SEQ(_KEY("RECT"), _VAR(_ARRAY("XY", 2), "Points"), Type="Rect"),
                                                     #_SEQ(_KEY("POLYGON"), _VAR(_ARRAY("XY"), "Points"), Type="Polygon")
                                                                ))), "Items"), _END_CMD, Type="Placement")),
    "SPECNETS": _STRUCT(_SEQ("SPECNETS_CMD", _VAR(_ARRAY("SPECNET_CMD"), "Items"),
                             "ENDSPECNETS_CMD", Type="SpecNet")),
    "SPECNETS_CMD": _SEQ(_KEY("SPECIALNETS"), _VAR(int, "Number"), _END_CMD),
    "ENDSPECNETS_CMD": _SEQ(_KEY("END"), _KEY("SPECIALNETS"), _EOL),
    "SPECNET_CMD": _STRUCT(_SEQ(_KEY("-"), _VAR(str, "Name"),
                                _VAR(_ARRAY("NETPIN"), "Pins"),
                                _NSEQ("SPECNETPARAM",
                                      _OPT(_VAR(_ARRAY("SPECWIRE"), "Wires")),
                                      ),
                                _OPT(_VAR(_ARRAY(_SEQ(_KEY("+"), _KEY("PROPERTY"),
                                                 _REPEAT(_STRUCT(_SEQ(_VAR(str, "Name"), _VAR(str, "Value"))))
                                                ), "NonEmpty"), "Properties")),
                                _END_CMD)),
    "SPECNETPARAM": _NSEQ(_OPT(_SEQ(_KEY("+"), _KEY("VOLTAGE"), _VAR(str, "Voltage"))),
                          _OPT(_SEQ(_KEY("+"), _KEY("SOURCE"),
                                    _VAR(_CHOICE(_KEY("DIST", "Dist"),
                                                 _KEY("NETLIST", "NetList"),
                                                 _KEY("TIMING", "Timing"),
                                                 _KEY("USER", "User")), "Source"))),
                          _OPT(_SEQ(_KEY("+"), _VAR(_KEY("FIXEDBUMP", True), "FixedBump"))),
                          _OPT(_SEQ(_KEY("+"), _KEY("ORIGINAL"), _VAR(str, "Net"))),
                          _OPT("USE"),
                          _OPT(_SEQ(_KEY("+"), _KEY("PATTERN"),
                                    _VAR(_CHOICE(_KEY("BALANCED", "Balanced"),
                                                _KEY("STEINER", "Steiner"),
                                                _KEY("TRUNK", "Trunk"),
                                                _KEY("WIREDLOGIC", "WiredLogic")), "Pattern"))),
                          _OPT(_SEQ(_KEY("+"), _KEY("ESTCAP"), _VAR(str, "WireCapacitance"))),
                          _OPT(_SEQ(_KEY("+"), _KEY("WEIGHT"), _VAR(str, "Weight"))),
                          ),
    "SPECWIRE": _STRUCT(_SEQ(_CHOICE(
                                _SEQ(_KEY("+"), _VAR(_KEY("COVER", True), "Cover")),
                                _SEQ(_KEY("+"), _VAR(_KEY("FIXED", True), "Fixed")),
                                _SEQ(_KEY("+"), _VAR(_KEY("ROUTED", True), "Routed")),
                                _SEQ(_KEY("+"), _KEY("SHIELD"), _VAR(str, "ShieldNet")),
                                ),
                             _CHOICE("SPECWIRE_SHAPES", "SPECWIRE_ROUTES"),
                            )),
    "SPECWIRE_SHAPES": _SEQ(_NSEQ(_OPT(_SEQ(_KEY("+"), _KEY("SHAPE"), _VAR(str, "ShapeType"))),
                                  _OPT(_SEQ(_KEY("+"), _KEY("MASK"), _VAR(int, "MaskNum")))),
                            _VAR(_ARRAY(_STRUCT(_CHOICE(
                                        _SEQ(_KEY("+"), _KEY("POLYGON"), _VAR(_ARRAY("XY"), "Points"), Type="Polygon"),
                                        _SEQ(_KEY("+"), _KEY("RECT"), _VAR(_ARRAY("XY",2), "Points"), Type="Rect"),
                                        _SEQ(_KEY("+"), _KEY("VIA"), _VAR(str, "Name"),
                                             _OPT(_VAR("ORIENT", "Orient")), _VAR(_ARRAY("XY"), "Points"), Type="Via"),
                                        )), "NonEmpty"), "Items")
                           ), 
    "SPECWIRE_ROUTES": _VAR(_ARRAY(_SEQ("SPECWIRE_ROUTE",
                                       _REPEAT(_SEQ(_KEY("NEW"), "SPECWIRE_ROUTE")))), "Routes"),
    "SPECWIRE_ROUTE": _STRUCT(_SEQ(_VAR(str, "Layer"), _VAR(int, "Width"),
                                   _OPT(_SEQ(_KEY("+"), _KEY("SHAPE"),
                                             _VAR(_CHOICE(_KEY("RING", "Ring"),
                                                          _KEY("PADRING", "PadRing"),
                                                          _KEY("BLOCKRING", "BlockRing"),
                                                          _KEY("STRIPE", "Stripe"),
                                                          _KEY("FOLLOWPIN", "FollowPin"),
                                                          _KEY("IOWIRE", "IOWire"),
                                                          _KEY("COREWIRE", "CoreWire"),
                                                          _KEY("BLOCKWIRE", "BlockWire"),
                                                          _KEY("BLOCKAGEWIRE", "BlockageWire"),
                                                          _KEY("FILLWIRE", "FillWire"),
                                                          _KEY("FILLWIREOPC", "FillWireOPC"),
                                                          _KEY("DRCFILL", "DRCFill"),
                                                          ), "Shape"))),
                                   _OPT(_SEQ(_KEY("+"), _KEY("STYLE"), _VAR(int, "StyleNum"))),
                                   _VAR(_ARRAY(_SEQ(_STRUCT("ROUTE_POINT"),
                                                    _REPEAT(_STRUCT(_CHOICE("ROUTE_TO_POINT", "ROUTE_TO_VIA")))
                                                    ), "NonEmpty"), "Items"),
                                   _EOL
                                 )),
    "ROUTE_POINT": _SEQ(_KEY("("), _VAR(int, "X"), _VAR(int, "Y"),
                        _OPT(_VAR(int, "ExtValue")), _KEY(")"), Start=True, Type="Point"),
    "ROUTE_TO_POINT": _SEQ(_OPT("MASKNUM"),"ROUTE_POINT", Start=False),
    "ROUTE_TO_VIA": _SEQ(_OPT("MASKNUM"), _NOTNEXT(_KEY("NEW")), _VAR(str, "ViaName"), _OPT("ORIENT"),
                        _OPT(_SEQ(_KEY("DO"), _VAR(int, "NX"), _KEY("BY"), _VAR(int, "NY"),
                                  _SEQ(_KEY("STEP"), _VAR(int, "DX"), _VAR(int, "DY")))), Type="Via"),
    "NETS": _STRUCT(_SEQ("NETS_CMD", _VAR(_ARRAY("NET_CMD"), "Items"), "ENDNETS_CMD", Type="Nets")),
    "NETS_CMD": _SEQ(_KEY("NETS"), _VAR(int, "Number"), _END_CMD),
    "ENDNETS_CMD": _SEQ(_KEY("END"), _KEY("NETS"), _EOL),
    "NETPIN": _STRUCT(_SEQ(_KEY("("),
                           _CHOICE(_SEQ(_KEY("PIN"), _VAR(str, "Pin")),
                                   _SEQ(_VAR(str, "Component"), _VAR(str, "Pin"))),
                           _OPT(_VAR(_KEY("SYNTHESIZED", True), "Synthesized")),
                           _KEY(")"))),
    "NET_CMD": _STRUCT(_SEQ(_KEY("-"),
                            _CHOICE(_SEQ(_KEY("MUSTJOIN"), _KEY("("), _VAR(str, "Component"), _VAR(str, "Pin"), _KEY(")")),
                                    _SEQ(_VAR(str, "Name"), _VAR(_ARRAY("NETPIN"), "Pins"))
                                    ),
                            #_REPEAT("SPECNETPARAM"),
                            #_OPT(_VAR(_ARRAY("SPECWIRE"), "Wires")),
                            "SPECNETPARAM",
                            _OPT(_VAR(_ARRAY(_SEQ(_KEY("+"), _KEY("PROPERTY"),
                                                  _REPEAT(_STRUCT(_SEQ(_VAR(str, "Name"), _VAR(str, "Value"))))
                                             ), "NonEmpty"), "Properties")),
                            _END_CMD)),
}

